<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title inertia>{{ App\Services\SettingsService::get('site_title', config('app.name', 'Laravel')) }}</title>
    <meta name="description" content="متجرك المتكامل لجميع مستلزمات الأطفال في أسيوط. نوفر تشكيلة واسعة من الببرونات, عربيات الأطفال, منتجات العناية, والملابس من أشهر الماركات العالمية مثل شيكو, بابلز, وسفاري.">
    <!-- Site Icon/Favicon -->
    @if (App\Services\SettingsService::get('site_icon'))
        @php
            $siteIcon = App\Services\SettingsService::get('site_icon');
            $iconUrl = str_starts_with($siteIcon, 'http') ? $siteIcon : asset('storage/' . $siteIcon);
        @endphp
        <link rel="icon" type="image/x-icon" href="{{ $iconUrl }}">
        <link rel="shortcut icon" type="image/x-icon" href="{{ $iconUrl }}">
    @endif

    <link rel="manifest" href="/manifest.json">
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
        rel="stylesheet">
    <!-- Scripts -->
    @routes
    @viteReactRefresh
    @vite(['resources/js/app.tsx', "resources/js/Pages/{$page['component']}.tsx"])
    @inertiaHead

    <!-- Facebook Pixel Code -->
    @if (App\Services\SettingsService::get('facebook_pixel_url'))
        <script>
            ! function(f, b, e, v, n, t, s) {
                if (f.fbq) return;
                n = f.fbq = function() {
                    n.callMethod ?
                        n.callMethod.apply(n, arguments) : n.queue.push(arguments)
                };
                if (!f._fbq) f._fbq = n;
                n.push = n;
                n.loaded = !0;
                n.version = '2.0';
                n.queue = [];
                t = b.createElement(e);
                t.async = !0;
                t.src = v;
                s = b.getElementsByTagName(e)[0];
                s.parentNode.insertBefore(t, s)
            }(window, document, 'script',
                '{{ App\Services\SettingsService::get('facebook_pixel_url') }}');

            @php
                $pixelId = App\Services\SettingsService::get('facebook_pixel_id');
            @endphp

            @if ($pixelId)
                fbq('init', '{{ $pixelId }}');
            @endif
            fbq('track', 'PageView');
        </script>
        <noscript>
            @if ($pixelId ?? false)
                <img height="1" width="1" style="display:none"
                    src="https://www.facebook.com/tr?id={{ $pixelId }}&ev=PageView&noscript=1" />
            @endif
        </noscript>
    @endif

    <style>
        /***************************************************
 * Generated by SVG Artista on 6/19/2025, 2:41:35 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/

        @-webkit-keyframes animate-svg-fill-1 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        @keyframes animate-svg-fill-1 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        .svg-elem-1 {
            -webkit-animation: animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
            animation: animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
        }

        @-webkit-keyframes animate-svg-fill-2 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        @keyframes animate-svg-fill-2 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        .svg-elem-2 {
            -webkit-animation: animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
            animation: animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.9s both;
        }

        @-webkit-keyframes animate-svg-fill-3 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        @keyframes animate-svg-fill-3 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        .svg-elem-3 {
            -webkit-animation: animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
            animation: animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1s both;
        }

        @-webkit-keyframes animate-svg-fill-4 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        @keyframes animate-svg-fill-4 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        .svg-elem-4 {
            -webkit-animation: animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s both;
            animation: animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.1s both;
        }

        @-webkit-keyframes animate-svg-fill-5 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        @keyframes animate-svg-fill-5 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        .svg-elem-5 {
            -webkit-animation: animate-svg-fill-5 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s both;
            animation: animate-svg-fill-5 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.2000000000000002s both;
        }

        @-webkit-keyframes animate-svg-fill-6 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        @keyframes animate-svg-fill-6 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        .svg-elem-6 {
            -webkit-animation: animate-svg-fill-6 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s both;
            animation: animate-svg-fill-6 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.3s both;
        }

        @-webkit-keyframes animate-svg-fill-7 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        @keyframes animate-svg-fill-7 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        .svg-elem-7 {
            -webkit-animation: animate-svg-fill-7 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4000000000000001s both;
            animation: animate-svg-fill-7 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.4000000000000001s both;
        }

        @-webkit-keyframes animate-svg-fill-8 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        @keyframes animate-svg-fill-8 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        .svg-elem-8 {
            -webkit-animation: animate-svg-fill-8 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s both;
            animation: animate-svg-fill-8 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 1.5s both;
        }
    </style>

    <style>
        .loading-container {
            height: 100vh;
            width: 100vw;
            overflow: hidden;
        }

        .logo-svg {
            position: fixed;
            top: 0;
            left: 0;
            height: 100%;
            width: 100%;
            background-color: #fff;
            display: flex;
            justify-content: center;
            align-items: center;
            z-index: 9999;
        }

        .loading-container.disabled {
            height: inherit;
            width: inherit;
            overflow: inherit;
        }

        .loading-container.disabled .logo-svg {
            display: none;
        }

        .logo-svg svg {
            width: 200px;
            height: 200px;
        }
    </style>
</head>

<body class="font-sans antialiased">
    <div class="loading-container">
        <div class="logo-svg">
            <svg id="section-logo-animation" class="active" version="1.0" xmlns="http://www.w3.org/2000/svg"
                width="100%" height="100%" viewBox="0 0 720.000000 720.000000" preserveAspectRatio="xMidYMid meet">

                <g transform="translate(0.000000,720.000000) scale(0.100000,-0.100000)" fill="#000000" stroke="none">
                    <path d="M0 5754 l0 -1445 53 3 52 3 3 1387 2 1388 613 2 612 3 3 53 3 52
-670 0 -671 0 0 -1446z" class="svg-elem-1"></path>
                    <path d="M2029 4180 c-9 -5 -86 -35 -170 -66 -85 -31 -156 -58 -158 -60 -3 -3
10 -19 28 -38 39 -40 45 -11 -72 -336 -46 -129 -99 -278 -117 -330 -18 -52
-36 -99 -41 -104 -4 -5 -28 34 -52 85 -25 52 -88 183 -141 293 -53 109 -96
203 -96 210 0 6 18 33 40 60 22 26 40 51 40 55 0 3 -101 6 -225 6 -124 0 -225
-2 -225 -5 0 -6 101 -96 132 -118 10 -7 24 -28 32 -45 8 -18 55 -124 106 -237
157 -348 190 -424 190 -433 0 -9 -59 -88 -75 -99 -22 -16 12 -18 218 -16 l215
3 -22 56 -23 55 63 150 c35 82 68 158 73 169 5 11 36 85 69 165 33 80 101 241
151 359 50 117 91 217 91 222 0 11 -11 11 -31 -1z" class="svg-elem-2"></path>
                    <path d="M5390 4069 c0 -4 18 -29 40 -57 l40 -50 0 -414 0 -414 -37 -31 c-21
-17 -56 -47 -78 -67 l-40 -35 240 0 240 -1 -70 44 c-38 24 -80 51 -92 60 l-23
17 0 339 c0 191 4 340 9 340 5 0 71 -107 147 -237 77 -130 158 -268 181 -307
23 -39 52 -88 63 -109 12 -21 37 -63 56 -93 l35 -54 94 0 95 0 0 483 1 482 40
40 40 40 -197 3 c-108 1 -199 1 -201 -2 -2 -2 30 -38 71 -79 l75 -76 1 -246
c1 -136 -1 -249 -3 -251 -2 -3 -18 17 -34 43 -275 442 -284 456 -308 488 -8
10 -15 23 -15 28 0 8 49 75 78 105 6 7 12 14 12 15 0 1 -104 2 -230 2 -127 0
-230 -3 -230 -6z" class="svg-elem-3"></path>
                    <path d="M2146 4028 c10 -13 21 -25 24 -28 3 -3 20 -24 38 -46 l32 -42 0 -389
0 -389 -50 -49 c-27 -27 -50 -53 -50 -57 0 -4 98 -8 217 -8 l217 0 -57 58 -57
58 0 377 0 377 48 67 c26 38 51 74 56 81 6 9 -40 12 -215 12 l-222 0 19 -22z" class="svg-elem-4"></path>
                    <path d="M2655 3983 l45 -68 0 -435 0 -435 358 2 c196 1 356 6 355 10 -5 27
-73 272 -81 292 -8 23 -13 17 -52 -67 -24 -51 -46 -92 -49 -92 -3 0 -80 -1
-171 -1 l-165 -1 -3 347 -2 347 42 76 c24 42 45 80 46 84 2 5 -80 8 -182 8
l-186 0 45 -67z" class="svg-elem-5"></path>
                    <path d="M3770 4045 c0 -3 14 -27 30 -53 17 -27 30 -55 30 -63 0 -26 -63 -279
-70 -279 -3 0 -25 18 -48 40 -22 22 -44 40 -47 40 -9 0 -95 -179 -87 -183 4
-2 35 -12 70 -22 34 -11 62 -22 62 -27 0 -4 -56 -109 -125 -233 -69 -124 -125
-230 -125 -236 0 -5 79 -9 195 -9 107 0 195 2 195 5 0 3 -15 36 -34 73 l-34
67 11 128 c6 80 14 127 21 126 6 0 38 -34 71 -75 33 -40 64 -74 69 -74 5 0 49
25 99 56 49 30 91 53 94 50 8 -8 93 -220 93 -233 0 -6 -18 -39 -40 -72 -22
-33 -40 -62 -40 -66 0 -3 92 -5 205 -5 113 0 205 2 205 4 0 2 -54 107 -120
233 -67 125 -123 238 -126 250 -5 17 4 32 35 62 23 22 41 44 41 50 0 12 -59
111 -66 111 -3 0 -14 -8 -25 -18 -23 -22 -67 -47 -73 -41 -10 11 -136 272
-136 281 0 6 14 33 30 60 17 26 30 50 30 53 0 3 -88 5 -195 5 -107 0 -195 -2
-195 -5z m233 -375 c37 -61 68 -114 70 -118 1 -4 -15 -28 -35 -55 l-36 -47
-69 56 c-37 31 -70 60 -71 65 -5 13 57 209 66 209 4 0 38 -50 75 -110z" class="svg-elem-6"></path>
                    <path d="M4722 4033 c8 -10 33 -41 56 -69 l42 -50 0 -389 0 -389 -57 -58 -57
-58 217 0 c119 0 217 3 217 8 0 4 -22 23 -49 42 -43 30 -49 40 -52 75 -2 22
-4 202 -4 400 l0 361 35 44 c19 25 37 47 40 50 3 3 14 15 24 28 l19 22 -223 0
c-211 0 -222 -1 -208 -17z" class="svg-elem-7"></path>
                    <path d="M7097 1723 c-4 -4 -7 -367 -7 -807 l0 -801 -1305 -3 -1305 -2 0 -55
0 -55 1360 0 1360 0 0 865 0 865 -48 0 c-27 0 -52 -3 -55 -7z" class="svg-elem-8"></path>
                </g>
            </svg>
        </div>
    </div>
    @inertia
</body>

</html>
