/* eslint-disable */
import * as types from './graphql';
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  fragment UserFields on User {\n    id\n    name\n    email\n    email_verified\n    phone\n    locale\n    is_admin\n    avatar\n    full_name\n    initials\n    has_social_accounts\n    linked_providers {\n      provider\n      provider_id\n    }\n  }\n": typeof types.UserFieldsFragmentDoc,
    "\n  query Me {\n    me {\n      ...UserFields\n    }\n  }\n": typeof types.MeDocument,
    "\n  mutation Login($input: LoginInput!) {\n    login(input: $input) {\n      access_token\n      token_type\n      expires_in\n      user {\n        ...UserFields\n      }\n    }\n  }\n": typeof types.LoginDocument,
    "\n  mutation Register($input: RegisterInput!) {\n    register(input: $input) {\n      access_token\n      token_type\n      expires_in\n      user {\n        ...UserFields\n      }\n    }\n  }\n": typeof types.RegisterDocument,
    "\n  mutation SocialLogin($input: SocialLoginInput!) {\n    socialLogin(input: $input) {\n      access_token\n      token_type\n      expires_in\n      user {\n        ...UserFields\n      }\n    }\n  }\n": typeof types.SocialLoginDocument,
    "\n  mutation Logout {\n    logout {\n      success\n      message\n    }\n  }\n": typeof types.LogoutDocument,
    "\n  mutation ForgotPassword($input: ForgotPasswordInput!) {\n    forgotPassword(input: $input) {\n      message\n    }\n  }\n": typeof types.ForgotPasswordDocument,
    "\n  mutation ResetPassword($input: ResetPasswordInput!) {\n    resetPassword(input: $input) {\n      success\n      message\n    }\n  }\n": typeof types.ResetPasswordDocument,
    "\n  mutation ChangePassword($input: ChangePasswordInput!) {\n    changePassword(input: $input) {\n      success\n      message\n    }\n  }\n": typeof types.ChangePasswordDocument,
    "\n  mutation UpdateProfile($input: UpdateProfileInput!) {\n    updateProfile(input: $input) {\n      ...UserFields\n    }\n  }\n": typeof types.UpdateProfileDocument,
    "\n  mutation VerifyEmail($input: VerifyEmailInput!) {\n    verifyEmail(input: $input) {\n      message\n      verified\n    }\n  }\n": typeof types.VerifyEmailDocument,
    "\n  mutation ResendVerification($input: ResendVerificationInput!) {\n    resendVerification(input: $input) {\n      success\n      message\n    }\n  }\n": typeof types.ResendVerificationDocument,
    "\n  mutation DeleteAccount {\n    deleteAccount {\n      success\n      message\n    }\n  }\n": typeof types.DeleteAccountDocument,
    "\n  mutation RefreshToken {\n    refreshToken {\n      access_token\n      token_type\n      expires_in\n      user {\n        ...UserFields\n      }\n    }\n  }\n": typeof types.RefreshTokenDocument,
    "\n  query CheckEmailAvailability($email: String!) {\n    checkEmailAvailability(email: $email)\n  }\n": typeof types.CheckEmailAvailabilityDocument,
    "\n  query Brands($is_active: Boolean, $parents_only: Boolean) {\n    brands(is_active: $is_active, parents_only: $parents_only) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n    }\n  }\n": typeof types.BrandsDocument,
    "\n  query BrandById($id: ID!) {\n    brand(id: $id) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n      }\n    }\n  }\n": typeof types.BrandByIdDocument,
    "\n  query BrandBySlug($slug: String!) {\n    brandBySlug(slug: $slug) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n      }\n    }\n  }\n": typeof types.BrandBySlugDocument,
    "\n  query GetCart {\n    cart {\n      id\n      user_id\n      session_id\n      total_price\n      total_items\n      total_quantity\n      is_empty\n      created_at\n      updated_at\n      items {\n        id\n        cart_id\n        product_variant_id\n        quantity\n        unit_price\n        total_price\n        is_available\n        created_at\n        updated_at\n        variant {\n          id\n          name\n          sku\n          price\n          sale_price\n          quantity\n          is_active\n          is_default\n          product {\n            id\n            name\n            slug\n            price\n            sale_price\n            effective_price\n            featured_image\n          }\n        }\n        product {\n          id\n          name\n          slug\n          price\n          sale_price\n          effective_price\n          featured_image\n          is_active\n          is_in_stock\n        }\n      }\n    }\n  }\n": typeof types.GetCartDocument,
    "\n  mutation AddToCart($input: AddToCartInput!) {\n    addToCart(input: $input) {\n      id\n      cart_id\n      product_variant_id\n      quantity\n      unit_price\n      total_price\n      is_available\n      variant {\n        id\n        name\n        sku\n        price\n        sale_price\n        quantity\n        is_active\n        is_default\n        product {\n          id\n          name\n          slug\n          price\n          sale_price\n          effective_price\n          featured_image\n        }\n      }\n      product {\n        id\n        name\n        slug\n        price\n        sale_price\n        effective_price\n        featured_image\n        is_active\n        is_in_stock\n      }\n    }\n  }\n": typeof types.AddToCartDocument,
    "\n  mutation UpdateCartItem($input: UpdateCartItemInput!) {\n    updateCartItem(input: $input) {\n      id\n      cart_id\n      product_variant_id\n      quantity\n      unit_price\n      total_price\n      is_available\n      variant {\n        id\n        name\n        sku\n        price\n        sale_price\n        quantity\n        is_active\n        is_default\n      }\n      product {\n        id\n        name\n        slug\n        price\n        sale_price\n        effective_price\n        featured_image\n        is_active\n        is_in_stock\n      }\n    }\n  }\n": typeof types.UpdateCartItemDocument,
    "\n  mutation RemoveFromCart($input: RemoveFromCartInput!) {\n    removeFromCart(input: $input)\n  }\n": typeof types.RemoveFromCartDocument,
    "\n  mutation ClearCart {\n    clearCart\n  }\n": typeof types.ClearCartDocument,
    "\n  query Categories($is_active: Boolean, $parents_only: Boolean) {\n    categories(is_active: $is_active, parents_only: $parents_only) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n    }\n  }\n": typeof types.CategoriesDocument,
    "\n  query CategoryById($id: ID!) {\n    category(id: $id) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n      }\n    }\n  }\n": typeof types.CategoryByIdDocument,
    "\n  query CategoryBySlug($slug: String!) {\n    categoryBySlug(slug: $slug) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n      }\n    }\n  }\n": typeof types.CategoryBySlugDocument,
    "\n  query NavigationData {\n    brands(is_active: true, parents_only: true) {\n      id\n      name\n      slug\n      display_image\n      display_order\n      is_active\n      active_products_count\n    }\n    categories(is_active: true, parents_only: true) {\n      id\n      name\n      slug\n      display_image\n      display_order\n      is_active\n      active_products_count\n    }\n  }\n": typeof types.NavigationDataDocument,
    "\n  query Products(\n    $search: ProductSearchInput\n    $orderBy: [ProductOrderByClause!]\n    $first: Int\n    $page: Int\n  ) {\n    products(\n      search: $search\n      orderBy: $orderBy\n      first: $first\n      page: $page\n    ) {\n      data {\n        id\n        name\n        slug\n        price\n        effective_price\n        discount_percentage\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n        description\n        category {\n          id\n          name\n        }\n        brand {\n          id\n          name\n        }\n        default_variant {\n          id\n          name\n          sku\n          price\n          effective_price\n          quantity\n          is_active\n          is_default\n        }\n      }\n      paginatorInfo {\n        count\n        currentPage\n        firstItem\n        hasMorePages\n        lastItem\n        lastPage\n        perPage\n        total\n      }\n    }\n  }\n": typeof types.ProductsDocument,
    "\n  query ProductById($id: ID!) {\n    product(id: $id) {\n      id\n      name\n      slug\n      description\n      price\n      effective_price\n      discount_percentage\n      is_featured\n      is_on_sale\n      is_in_stock\n      featured_image\n      images\n      category {\n        id\n        name\n        slug\n      }\n      brand {\n        id\n        name\n        slug\n      }\n      variants {\n        id\n        name\n        price\n        effective_price\n        is_in_stock\n        quantity\n        attributes\n      }\n      default_variant {\n        id\n        name\n        sku\n        price\n        effective_price\n        quantity\n        is_active\n        is_default\n      }\n    }\n  }\n": typeof types.ProductByIdDocument,
    "\n  query ProductBySlug($slug: String!) {\n    productBySlug(slug: $slug) {\n      id\n      name\n      slug\n      description\n      price\n      effective_price\n      discount_percentage\n      is_featured\n      is_on_sale\n      is_in_stock\n      featured_image\n      images\n      category {\n        id\n        name\n        slug\n      }\n      brand {\n        id\n        name\n        slug\n      }\n      variants {\n        id\n        name\n        price\n        effective_price\n        is_in_stock\n        quantity\n        attributes\n      }\n      default_variant {\n        id\n        name\n        sku\n        price\n        effective_price\n        quantity\n        is_active\n        is_default\n      }\n    }\n  }\n": typeof types.ProductBySlugDocument,
    "\n  query Sections($active: Boolean) {\n    sections(active: $active) {\n      id\n      title\n      title_en\n      title_ar\n      active\n      sort_order\n      section_type\n      created_at\n      updated_at\n      products_count\n      active_products_count\n      has_products\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        discount_percentage\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n        description\n        category {\n          id\n          name\n          slug\n        }\n        brand {\n          id\n          name\n          slug\n        }\n      }\n    }\n  }\n": typeof types.SectionsDocument,
    "\n  query SectionById($id: ID!) {\n    section(id: $id) {\n      id\n      title\n      title_en\n      title_ar\n      active\n      sort_order\n      section_type\n      created_at\n      updated_at\n      products_count\n      active_products_count\n      has_products\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        discount_percentage\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n        description\n        category {\n          id\n          name\n          slug\n        }\n        brand {\n          id\n          name\n          slug\n        }\n      }\n    }\n  }\n": typeof types.SectionByIdDocument,
    "\n  query GetWishlist {\n    wishlist {\n      id\n      user_id\n      product_id\n      created_at\n      product {\n        id\n        name\n        slug\n        price\n        sale_price\n        effective_price\n        featured_image\n        is_active\n        is_in_stock\n        category {\n          id\n          name\n        }\n        brand {\n          id\n          name\n        }\n        default_variant {\n          id\n          name\n          sku\n          price\n          sale_price\n          quantity\n          is_active\n          is_default\n        }\n      }\n    }\n  }\n": typeof types.GetWishlistDocument,
    "\n  query GetWishlistCount {\n    wishlistCount\n  }\n": typeof types.GetWishlistCountDocument,
    "\n  mutation AddToWishlist($input: AddToWishlistInput!) {\n    addToWishlist(input: $input) {\n      id\n      user_id\n      product_id\n      created_at\n      product {\n        id\n        name\n        slug\n        price\n        sale_price\n        effective_price\n        featured_image\n        is_active\n        is_in_stock\n        category {\n          id\n          name\n        }\n        brand {\n          id\n          name\n        }\n        default_variant {\n          id\n          name\n          sku\n          price\n          sale_price\n          quantity\n          is_active\n          is_default\n        }\n      }\n    }\n  }\n": typeof types.AddToWishlistDocument,
    "\n  mutation RemoveFromWishlist($input: RemoveFromWishlistInput!) {\n    removeFromWishlist(input: $input)\n  }\n": typeof types.RemoveFromWishlistDocument,
    "\n  mutation MoveWishlistToCart(\n    $product_id: ID!\n    $product_variant_id: ID!\n    $quantity: Int!\n  ) {\n    moveWishlistToCart(\n      product_id: $product_id\n      product_variant_id: $product_variant_id\n      quantity: $quantity\n    ) {\n      id\n      cart_id\n      product_variant_id\n      quantity\n      unit_price\n      total_price\n      is_available\n      variant {\n        id\n        name\n        sku\n        price\n        sale_price\n        quantity\n        is_active\n        is_default\n      }\n      product {\n        id\n        name\n        slug\n        price\n        sale_price\n        effective_price\n        featured_image\n        is_active\n        is_in_stock\n      }\n    }\n  }\n": typeof types.MoveWishlistToCartDocument,
    "\n  query GetNotifications($first: Int = 10, $page: Int = 1, $unread_only: Boolean = false) {\n    notifications(first: $first, page: $page, unread_only: $unread_only) {\n      data {\n        id\n        type\n        data\n        read_at\n        created_at\n        updated_at\n      }\n      paginatorInfo {\n        count\n        currentPage\n        firstItem\n        hasMorePages\n        lastItem\n        lastPage\n        perPage\n        total\n      }\n    }\n  }\n": typeof types.GetNotificationsDocument,
    "\n  query GetUnreadNotificationsCount {\n    unreadNotificationsCount\n  }\n": typeof types.GetUnreadNotificationsCountDocument,
    "\n  mutation MarkNotificationAsRead($id: ID!) {\n    markNotificationAsRead(id: $id)\n  }\n": typeof types.MarkNotificationAsReadDocument,
    "\n  mutation MarkAllNotificationsAsRead {\n    markAllNotificationsAsRead\n  }\n": typeof types.MarkAllNotificationsAsReadDocument,
    "\n  mutation DeleteNotification($id: ID!) {\n    deleteNotification(id: $id)\n  }\n": typeof types.DeleteNotificationDocument,
    "\n  mutation SendNotification($user_id: ID!, $notification: NotificationInput!) {\n    sendNotification(user_id: $user_id, notification: $notification)\n  }\n": typeof types.SendNotificationDocument,
};
const documents: Documents = {
    "\n  fragment UserFields on User {\n    id\n    name\n    email\n    email_verified\n    phone\n    locale\n    is_admin\n    avatar\n    full_name\n    initials\n    has_social_accounts\n    linked_providers {\n      provider\n      provider_id\n    }\n  }\n": types.UserFieldsFragmentDoc,
    "\n  query Me {\n    me {\n      ...UserFields\n    }\n  }\n": types.MeDocument,
    "\n  mutation Login($input: LoginInput!) {\n    login(input: $input) {\n      access_token\n      token_type\n      expires_in\n      user {\n        ...UserFields\n      }\n    }\n  }\n": types.LoginDocument,
    "\n  mutation Register($input: RegisterInput!) {\n    register(input: $input) {\n      access_token\n      token_type\n      expires_in\n      user {\n        ...UserFields\n      }\n    }\n  }\n": types.RegisterDocument,
    "\n  mutation SocialLogin($input: SocialLoginInput!) {\n    socialLogin(input: $input) {\n      access_token\n      token_type\n      expires_in\n      user {\n        ...UserFields\n      }\n    }\n  }\n": types.SocialLoginDocument,
    "\n  mutation Logout {\n    logout {\n      success\n      message\n    }\n  }\n": types.LogoutDocument,
    "\n  mutation ForgotPassword($input: ForgotPasswordInput!) {\n    forgotPassword(input: $input) {\n      message\n    }\n  }\n": types.ForgotPasswordDocument,
    "\n  mutation ResetPassword($input: ResetPasswordInput!) {\n    resetPassword(input: $input) {\n      success\n      message\n    }\n  }\n": types.ResetPasswordDocument,
    "\n  mutation ChangePassword($input: ChangePasswordInput!) {\n    changePassword(input: $input) {\n      success\n      message\n    }\n  }\n": types.ChangePasswordDocument,
    "\n  mutation UpdateProfile($input: UpdateProfileInput!) {\n    updateProfile(input: $input) {\n      ...UserFields\n    }\n  }\n": types.UpdateProfileDocument,
    "\n  mutation VerifyEmail($input: VerifyEmailInput!) {\n    verifyEmail(input: $input) {\n      message\n      verified\n    }\n  }\n": types.VerifyEmailDocument,
    "\n  mutation ResendVerification($input: ResendVerificationInput!) {\n    resendVerification(input: $input) {\n      success\n      message\n    }\n  }\n": types.ResendVerificationDocument,
    "\n  mutation DeleteAccount {\n    deleteAccount {\n      success\n      message\n    }\n  }\n": types.DeleteAccountDocument,
    "\n  mutation RefreshToken {\n    refreshToken {\n      access_token\n      token_type\n      expires_in\n      user {\n        ...UserFields\n      }\n    }\n  }\n": types.RefreshTokenDocument,
    "\n  query CheckEmailAvailability($email: String!) {\n    checkEmailAvailability(email: $email)\n  }\n": types.CheckEmailAvailabilityDocument,
    "\n  query Brands($is_active: Boolean, $parents_only: Boolean) {\n    brands(is_active: $is_active, parents_only: $parents_only) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n    }\n  }\n": types.BrandsDocument,
    "\n  query BrandById($id: ID!) {\n    brand(id: $id) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n      }\n    }\n  }\n": types.BrandByIdDocument,
    "\n  query BrandBySlug($slug: String!) {\n    brandBySlug(slug: $slug) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n      }\n    }\n  }\n": types.BrandBySlugDocument,
    "\n  query GetCart {\n    cart {\n      id\n      user_id\n      session_id\n      total_price\n      total_items\n      total_quantity\n      is_empty\n      created_at\n      updated_at\n      items {\n        id\n        cart_id\n        product_variant_id\n        quantity\n        unit_price\n        total_price\n        is_available\n        created_at\n        updated_at\n        variant {\n          id\n          name\n          sku\n          price\n          sale_price\n          quantity\n          is_active\n          is_default\n          product {\n            id\n            name\n            slug\n            price\n            sale_price\n            effective_price\n            featured_image\n          }\n        }\n        product {\n          id\n          name\n          slug\n          price\n          sale_price\n          effective_price\n          featured_image\n          is_active\n          is_in_stock\n        }\n      }\n    }\n  }\n": types.GetCartDocument,
    "\n  mutation AddToCart($input: AddToCartInput!) {\n    addToCart(input: $input) {\n      id\n      cart_id\n      product_variant_id\n      quantity\n      unit_price\n      total_price\n      is_available\n      variant {\n        id\n        name\n        sku\n        price\n        sale_price\n        quantity\n        is_active\n        is_default\n        product {\n          id\n          name\n          slug\n          price\n          sale_price\n          effective_price\n          featured_image\n        }\n      }\n      product {\n        id\n        name\n        slug\n        price\n        sale_price\n        effective_price\n        featured_image\n        is_active\n        is_in_stock\n      }\n    }\n  }\n": types.AddToCartDocument,
    "\n  mutation UpdateCartItem($input: UpdateCartItemInput!) {\n    updateCartItem(input: $input) {\n      id\n      cart_id\n      product_variant_id\n      quantity\n      unit_price\n      total_price\n      is_available\n      variant {\n        id\n        name\n        sku\n        price\n        sale_price\n        quantity\n        is_active\n        is_default\n      }\n      product {\n        id\n        name\n        slug\n        price\n        sale_price\n        effective_price\n        featured_image\n        is_active\n        is_in_stock\n      }\n    }\n  }\n": types.UpdateCartItemDocument,
    "\n  mutation RemoveFromCart($input: RemoveFromCartInput!) {\n    removeFromCart(input: $input)\n  }\n": types.RemoveFromCartDocument,
    "\n  mutation ClearCart {\n    clearCart\n  }\n": types.ClearCartDocument,
    "\n  query Categories($is_active: Boolean, $parents_only: Boolean) {\n    categories(is_active: $is_active, parents_only: $parents_only) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n    }\n  }\n": types.CategoriesDocument,
    "\n  query CategoryById($id: ID!) {\n    category(id: $id) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n      }\n    }\n  }\n": types.CategoryByIdDocument,
    "\n  query CategoryBySlug($slug: String!) {\n    categoryBySlug(slug: $slug) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n      }\n    }\n  }\n": types.CategoryBySlugDocument,
    "\n  query NavigationData {\n    brands(is_active: true, parents_only: true) {\n      id\n      name\n      slug\n      display_image\n      display_order\n      is_active\n      active_products_count\n    }\n    categories(is_active: true, parents_only: true) {\n      id\n      name\n      slug\n      display_image\n      display_order\n      is_active\n      active_products_count\n    }\n  }\n": types.NavigationDataDocument,
    "\n  query Products(\n    $search: ProductSearchInput\n    $orderBy: [ProductOrderByClause!]\n    $first: Int\n    $page: Int\n  ) {\n    products(\n      search: $search\n      orderBy: $orderBy\n      first: $first\n      page: $page\n    ) {\n      data {\n        id\n        name\n        slug\n        price\n        effective_price\n        discount_percentage\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n        description\n        category {\n          id\n          name\n        }\n        brand {\n          id\n          name\n        }\n        default_variant {\n          id\n          name\n          sku\n          price\n          effective_price\n          quantity\n          is_active\n          is_default\n        }\n      }\n      paginatorInfo {\n        count\n        currentPage\n        firstItem\n        hasMorePages\n        lastItem\n        lastPage\n        perPage\n        total\n      }\n    }\n  }\n": types.ProductsDocument,
    "\n  query ProductById($id: ID!) {\n    product(id: $id) {\n      id\n      name\n      slug\n      description\n      price\n      effective_price\n      discount_percentage\n      is_featured\n      is_on_sale\n      is_in_stock\n      featured_image\n      images\n      category {\n        id\n        name\n        slug\n      }\n      brand {\n        id\n        name\n        slug\n      }\n      variants {\n        id\n        name\n        price\n        effective_price\n        is_in_stock\n        quantity\n        attributes\n      }\n      default_variant {\n        id\n        name\n        sku\n        price\n        effective_price\n        quantity\n        is_active\n        is_default\n      }\n    }\n  }\n": types.ProductByIdDocument,
    "\n  query ProductBySlug($slug: String!) {\n    productBySlug(slug: $slug) {\n      id\n      name\n      slug\n      description\n      price\n      effective_price\n      discount_percentage\n      is_featured\n      is_on_sale\n      is_in_stock\n      featured_image\n      images\n      category {\n        id\n        name\n        slug\n      }\n      brand {\n        id\n        name\n        slug\n      }\n      variants {\n        id\n        name\n        price\n        effective_price\n        is_in_stock\n        quantity\n        attributes\n      }\n      default_variant {\n        id\n        name\n        sku\n        price\n        effective_price\n        quantity\n        is_active\n        is_default\n      }\n    }\n  }\n": types.ProductBySlugDocument,
    "\n  query Sections($active: Boolean) {\n    sections(active: $active) {\n      id\n      title\n      title_en\n      title_ar\n      active\n      sort_order\n      section_type\n      created_at\n      updated_at\n      products_count\n      active_products_count\n      has_products\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        discount_percentage\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n        description\n        category {\n          id\n          name\n          slug\n        }\n        brand {\n          id\n          name\n          slug\n        }\n      }\n    }\n  }\n": types.SectionsDocument,
    "\n  query SectionById($id: ID!) {\n    section(id: $id) {\n      id\n      title\n      title_en\n      title_ar\n      active\n      sort_order\n      section_type\n      created_at\n      updated_at\n      products_count\n      active_products_count\n      has_products\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        discount_percentage\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n        description\n        category {\n          id\n          name\n          slug\n        }\n        brand {\n          id\n          name\n          slug\n        }\n      }\n    }\n  }\n": types.SectionByIdDocument,
    "\n  query GetWishlist {\n    wishlist {\n      id\n      user_id\n      product_id\n      created_at\n      product {\n        id\n        name\n        slug\n        price\n        sale_price\n        effective_price\n        featured_image\n        is_active\n        is_in_stock\n        category {\n          id\n          name\n        }\n        brand {\n          id\n          name\n        }\n        default_variant {\n          id\n          name\n          sku\n          price\n          sale_price\n          quantity\n          is_active\n          is_default\n        }\n      }\n    }\n  }\n": types.GetWishlistDocument,
    "\n  query GetWishlistCount {\n    wishlistCount\n  }\n": types.GetWishlistCountDocument,
    "\n  mutation AddToWishlist($input: AddToWishlistInput!) {\n    addToWishlist(input: $input) {\n      id\n      user_id\n      product_id\n      created_at\n      product {\n        id\n        name\n        slug\n        price\n        sale_price\n        effective_price\n        featured_image\n        is_active\n        is_in_stock\n        category {\n          id\n          name\n        }\n        brand {\n          id\n          name\n        }\n        default_variant {\n          id\n          name\n          sku\n          price\n          sale_price\n          quantity\n          is_active\n          is_default\n        }\n      }\n    }\n  }\n": types.AddToWishlistDocument,
    "\n  mutation RemoveFromWishlist($input: RemoveFromWishlistInput!) {\n    removeFromWishlist(input: $input)\n  }\n": types.RemoveFromWishlistDocument,
    "\n  mutation MoveWishlistToCart(\n    $product_id: ID!\n    $product_variant_id: ID!\n    $quantity: Int!\n  ) {\n    moveWishlistToCart(\n      product_id: $product_id\n      product_variant_id: $product_variant_id\n      quantity: $quantity\n    ) {\n      id\n      cart_id\n      product_variant_id\n      quantity\n      unit_price\n      total_price\n      is_available\n      variant {\n        id\n        name\n        sku\n        price\n        sale_price\n        quantity\n        is_active\n        is_default\n      }\n      product {\n        id\n        name\n        slug\n        price\n        sale_price\n        effective_price\n        featured_image\n        is_active\n        is_in_stock\n      }\n    }\n  }\n": types.MoveWishlistToCartDocument,
    "\n  query GetNotifications($first: Int = 10, $page: Int = 1, $unread_only: Boolean = false) {\n    notifications(first: $first, page: $page, unread_only: $unread_only) {\n      data {\n        id\n        type\n        data\n        read_at\n        created_at\n        updated_at\n      }\n      paginatorInfo {\n        count\n        currentPage\n        firstItem\n        hasMorePages\n        lastItem\n        lastPage\n        perPage\n        total\n      }\n    }\n  }\n": types.GetNotificationsDocument,
    "\n  query GetUnreadNotificationsCount {\n    unreadNotificationsCount\n  }\n": types.GetUnreadNotificationsCountDocument,
    "\n  mutation MarkNotificationAsRead($id: ID!) {\n    markNotificationAsRead(id: $id)\n  }\n": types.MarkNotificationAsReadDocument,
    "\n  mutation MarkAllNotificationsAsRead {\n    markAllNotificationsAsRead\n  }\n": types.MarkAllNotificationsAsReadDocument,
    "\n  mutation DeleteNotification($id: ID!) {\n    deleteNotification(id: $id)\n  }\n": types.DeleteNotificationDocument,
    "\n  mutation SendNotification($user_id: ID!, $notification: NotificationInput!) {\n    sendNotification(user_id: $user_id, notification: $notification)\n  }\n": types.SendNotificationDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment UserFields on User {\n    id\n    name\n    email\n    email_verified\n    phone\n    locale\n    is_admin\n    avatar\n    full_name\n    initials\n    has_social_accounts\n    linked_providers {\n      provider\n      provider_id\n    }\n  }\n"): (typeof documents)["\n  fragment UserFields on User {\n    id\n    name\n    email\n    email_verified\n    phone\n    locale\n    is_admin\n    avatar\n    full_name\n    initials\n    has_social_accounts\n    linked_providers {\n      provider\n      provider_id\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Me {\n    me {\n      ...UserFields\n    }\n  }\n"): (typeof documents)["\n  query Me {\n    me {\n      ...UserFields\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation Login($input: LoginInput!) {\n    login(input: $input) {\n      access_token\n      token_type\n      expires_in\n      user {\n        ...UserFields\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation Login($input: LoginInput!) {\n    login(input: $input) {\n      access_token\n      token_type\n      expires_in\n      user {\n        ...UserFields\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation Register($input: RegisterInput!) {\n    register(input: $input) {\n      access_token\n      token_type\n      expires_in\n      user {\n        ...UserFields\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation Register($input: RegisterInput!) {\n    register(input: $input) {\n      access_token\n      token_type\n      expires_in\n      user {\n        ...UserFields\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation SocialLogin($input: SocialLoginInput!) {\n    socialLogin(input: $input) {\n      access_token\n      token_type\n      expires_in\n      user {\n        ...UserFields\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation SocialLogin($input: SocialLoginInput!) {\n    socialLogin(input: $input) {\n      access_token\n      token_type\n      expires_in\n      user {\n        ...UserFields\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation Logout {\n    logout {\n      success\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation Logout {\n    logout {\n      success\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ForgotPassword($input: ForgotPasswordInput!) {\n    forgotPassword(input: $input) {\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation ForgotPassword($input: ForgotPasswordInput!) {\n    forgotPassword(input: $input) {\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ResetPassword($input: ResetPasswordInput!) {\n    resetPassword(input: $input) {\n      success\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation ResetPassword($input: ResetPasswordInput!) {\n    resetPassword(input: $input) {\n      success\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ChangePassword($input: ChangePasswordInput!) {\n    changePassword(input: $input) {\n      success\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation ChangePassword($input: ChangePasswordInput!) {\n    changePassword(input: $input) {\n      success\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateProfile($input: UpdateProfileInput!) {\n    updateProfile(input: $input) {\n      ...UserFields\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateProfile($input: UpdateProfileInput!) {\n    updateProfile(input: $input) {\n      ...UserFields\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation VerifyEmail($input: VerifyEmailInput!) {\n    verifyEmail(input: $input) {\n      message\n      verified\n    }\n  }\n"): (typeof documents)["\n  mutation VerifyEmail($input: VerifyEmailInput!) {\n    verifyEmail(input: $input) {\n      message\n      verified\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ResendVerification($input: ResendVerificationInput!) {\n    resendVerification(input: $input) {\n      success\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation ResendVerification($input: ResendVerificationInput!) {\n    resendVerification(input: $input) {\n      success\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DeleteAccount {\n    deleteAccount {\n      success\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation DeleteAccount {\n    deleteAccount {\n      success\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RefreshToken {\n    refreshToken {\n      access_token\n      token_type\n      expires_in\n      user {\n        ...UserFields\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation RefreshToken {\n    refreshToken {\n      access_token\n      token_type\n      expires_in\n      user {\n        ...UserFields\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CheckEmailAvailability($email: String!) {\n    checkEmailAvailability(email: $email)\n  }\n"): (typeof documents)["\n  query CheckEmailAvailability($email: String!) {\n    checkEmailAvailability(email: $email)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Brands($is_active: Boolean, $parents_only: Boolean) {\n    brands(is_active: $is_active, parents_only: $parents_only) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n    }\n  }\n"): (typeof documents)["\n  query Brands($is_active: Boolean, $parents_only: Boolean) {\n    brands(is_active: $is_active, parents_only: $parents_only) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query BrandById($id: ID!) {\n    brand(id: $id) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n      }\n    }\n  }\n"): (typeof documents)["\n  query BrandById($id: ID!) {\n    brand(id: $id) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query BrandBySlug($slug: String!) {\n    brandBySlug(slug: $slug) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n      }\n    }\n  }\n"): (typeof documents)["\n  query BrandBySlug($slug: String!) {\n    brandBySlug(slug: $slug) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetCart {\n    cart {\n      id\n      user_id\n      session_id\n      total_price\n      total_items\n      total_quantity\n      is_empty\n      created_at\n      updated_at\n      items {\n        id\n        cart_id\n        product_variant_id\n        quantity\n        unit_price\n        total_price\n        is_available\n        created_at\n        updated_at\n        variant {\n          id\n          name\n          sku\n          price\n          sale_price\n          quantity\n          is_active\n          is_default\n          product {\n            id\n            name\n            slug\n            price\n            sale_price\n            effective_price\n            featured_image\n          }\n        }\n        product {\n          id\n          name\n          slug\n          price\n          sale_price\n          effective_price\n          featured_image\n          is_active\n          is_in_stock\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetCart {\n    cart {\n      id\n      user_id\n      session_id\n      total_price\n      total_items\n      total_quantity\n      is_empty\n      created_at\n      updated_at\n      items {\n        id\n        cart_id\n        product_variant_id\n        quantity\n        unit_price\n        total_price\n        is_available\n        created_at\n        updated_at\n        variant {\n          id\n          name\n          sku\n          price\n          sale_price\n          quantity\n          is_active\n          is_default\n          product {\n            id\n            name\n            slug\n            price\n            sale_price\n            effective_price\n            featured_image\n          }\n        }\n        product {\n          id\n          name\n          slug\n          price\n          sale_price\n          effective_price\n          featured_image\n          is_active\n          is_in_stock\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation AddToCart($input: AddToCartInput!) {\n    addToCart(input: $input) {\n      id\n      cart_id\n      product_variant_id\n      quantity\n      unit_price\n      total_price\n      is_available\n      variant {\n        id\n        name\n        sku\n        price\n        sale_price\n        quantity\n        is_active\n        is_default\n        product {\n          id\n          name\n          slug\n          price\n          sale_price\n          effective_price\n          featured_image\n        }\n      }\n      product {\n        id\n        name\n        slug\n        price\n        sale_price\n        effective_price\n        featured_image\n        is_active\n        is_in_stock\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation AddToCart($input: AddToCartInput!) {\n    addToCart(input: $input) {\n      id\n      cart_id\n      product_variant_id\n      quantity\n      unit_price\n      total_price\n      is_available\n      variant {\n        id\n        name\n        sku\n        price\n        sale_price\n        quantity\n        is_active\n        is_default\n        product {\n          id\n          name\n          slug\n          price\n          sale_price\n          effective_price\n          featured_image\n        }\n      }\n      product {\n        id\n        name\n        slug\n        price\n        sale_price\n        effective_price\n        featured_image\n        is_active\n        is_in_stock\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateCartItem($input: UpdateCartItemInput!) {\n    updateCartItem(input: $input) {\n      id\n      cart_id\n      product_variant_id\n      quantity\n      unit_price\n      total_price\n      is_available\n      variant {\n        id\n        name\n        sku\n        price\n        sale_price\n        quantity\n        is_active\n        is_default\n      }\n      product {\n        id\n        name\n        slug\n        price\n        sale_price\n        effective_price\n        featured_image\n        is_active\n        is_in_stock\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateCartItem($input: UpdateCartItemInput!) {\n    updateCartItem(input: $input) {\n      id\n      cart_id\n      product_variant_id\n      quantity\n      unit_price\n      total_price\n      is_available\n      variant {\n        id\n        name\n        sku\n        price\n        sale_price\n        quantity\n        is_active\n        is_default\n      }\n      product {\n        id\n        name\n        slug\n        price\n        sale_price\n        effective_price\n        featured_image\n        is_active\n        is_in_stock\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RemoveFromCart($input: RemoveFromCartInput!) {\n    removeFromCart(input: $input)\n  }\n"): (typeof documents)["\n  mutation RemoveFromCart($input: RemoveFromCartInput!) {\n    removeFromCart(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ClearCart {\n    clearCart\n  }\n"): (typeof documents)["\n  mutation ClearCart {\n    clearCart\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Categories($is_active: Boolean, $parents_only: Boolean) {\n    categories(is_active: $is_active, parents_only: $parents_only) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n    }\n  }\n"): (typeof documents)["\n  query Categories($is_active: Boolean, $parents_only: Boolean) {\n    categories(is_active: $is_active, parents_only: $parents_only) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CategoryById($id: ID!) {\n    category(id: $id) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n      }\n    }\n  }\n"): (typeof documents)["\n  query CategoryById($id: ID!) {\n    category(id: $id) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query CategoryBySlug($slug: String!) {\n    categoryBySlug(slug: $slug) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n      }\n    }\n  }\n"): (typeof documents)["\n  query CategoryBySlug($slug: String!) {\n    categoryBySlug(slug: $slug) {\n      id\n      name\n      slug\n      description\n      display_image\n      display_order\n      is_active\n      url\n      products_count\n      active_products_count\n      has_products\n      parent_id\n      parent {\n        id\n        name\n        slug\n      }\n      children {\n        id\n        name\n        slug\n        active_products_count\n      }\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query NavigationData {\n    brands(is_active: true, parents_only: true) {\n      id\n      name\n      slug\n      display_image\n      display_order\n      is_active\n      active_products_count\n    }\n    categories(is_active: true, parents_only: true) {\n      id\n      name\n      slug\n      display_image\n      display_order\n      is_active\n      active_products_count\n    }\n  }\n"): (typeof documents)["\n  query NavigationData {\n    brands(is_active: true, parents_only: true) {\n      id\n      name\n      slug\n      display_image\n      display_order\n      is_active\n      active_products_count\n    }\n    categories(is_active: true, parents_only: true) {\n      id\n      name\n      slug\n      display_image\n      display_order\n      is_active\n      active_products_count\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Products(\n    $search: ProductSearchInput\n    $orderBy: [ProductOrderByClause!]\n    $first: Int\n    $page: Int\n  ) {\n    products(\n      search: $search\n      orderBy: $orderBy\n      first: $first\n      page: $page\n    ) {\n      data {\n        id\n        name\n        slug\n        price\n        effective_price\n        discount_percentage\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n        description\n        category {\n          id\n          name\n        }\n        brand {\n          id\n          name\n        }\n        default_variant {\n          id\n          name\n          sku\n          price\n          effective_price\n          quantity\n          is_active\n          is_default\n        }\n      }\n      paginatorInfo {\n        count\n        currentPage\n        firstItem\n        hasMorePages\n        lastItem\n        lastPage\n        perPage\n        total\n      }\n    }\n  }\n"): (typeof documents)["\n  query Products(\n    $search: ProductSearchInput\n    $orderBy: [ProductOrderByClause!]\n    $first: Int\n    $page: Int\n  ) {\n    products(\n      search: $search\n      orderBy: $orderBy\n      first: $first\n      page: $page\n    ) {\n      data {\n        id\n        name\n        slug\n        price\n        effective_price\n        discount_percentage\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n        description\n        category {\n          id\n          name\n        }\n        brand {\n          id\n          name\n        }\n        default_variant {\n          id\n          name\n          sku\n          price\n          effective_price\n          quantity\n          is_active\n          is_default\n        }\n      }\n      paginatorInfo {\n        count\n        currentPage\n        firstItem\n        hasMorePages\n        lastItem\n        lastPage\n        perPage\n        total\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProductById($id: ID!) {\n    product(id: $id) {\n      id\n      name\n      slug\n      description\n      price\n      effective_price\n      discount_percentage\n      is_featured\n      is_on_sale\n      is_in_stock\n      featured_image\n      images\n      category {\n        id\n        name\n        slug\n      }\n      brand {\n        id\n        name\n        slug\n      }\n      variants {\n        id\n        name\n        price\n        effective_price\n        is_in_stock\n        quantity\n        attributes\n      }\n      default_variant {\n        id\n        name\n        sku\n        price\n        effective_price\n        quantity\n        is_active\n        is_default\n      }\n    }\n  }\n"): (typeof documents)["\n  query ProductById($id: ID!) {\n    product(id: $id) {\n      id\n      name\n      slug\n      description\n      price\n      effective_price\n      discount_percentage\n      is_featured\n      is_on_sale\n      is_in_stock\n      featured_image\n      images\n      category {\n        id\n        name\n        slug\n      }\n      brand {\n        id\n        name\n        slug\n      }\n      variants {\n        id\n        name\n        price\n        effective_price\n        is_in_stock\n        quantity\n        attributes\n      }\n      default_variant {\n        id\n        name\n        sku\n        price\n        effective_price\n        quantity\n        is_active\n        is_default\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ProductBySlug($slug: String!) {\n    productBySlug(slug: $slug) {\n      id\n      name\n      slug\n      description\n      price\n      effective_price\n      discount_percentage\n      is_featured\n      is_on_sale\n      is_in_stock\n      featured_image\n      images\n      category {\n        id\n        name\n        slug\n      }\n      brand {\n        id\n        name\n        slug\n      }\n      variants {\n        id\n        name\n        price\n        effective_price\n        is_in_stock\n        quantity\n        attributes\n      }\n      default_variant {\n        id\n        name\n        sku\n        price\n        effective_price\n        quantity\n        is_active\n        is_default\n      }\n    }\n  }\n"): (typeof documents)["\n  query ProductBySlug($slug: String!) {\n    productBySlug(slug: $slug) {\n      id\n      name\n      slug\n      description\n      price\n      effective_price\n      discount_percentage\n      is_featured\n      is_on_sale\n      is_in_stock\n      featured_image\n      images\n      category {\n        id\n        name\n        slug\n      }\n      brand {\n        id\n        name\n        slug\n      }\n      variants {\n        id\n        name\n        price\n        effective_price\n        is_in_stock\n        quantity\n        attributes\n      }\n      default_variant {\n        id\n        name\n        sku\n        price\n        effective_price\n        quantity\n        is_active\n        is_default\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Sections($active: Boolean) {\n    sections(active: $active) {\n      id\n      title\n      title_en\n      title_ar\n      active\n      sort_order\n      section_type\n      created_at\n      updated_at\n      products_count\n      active_products_count\n      has_products\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        discount_percentage\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n        description\n        category {\n          id\n          name\n          slug\n        }\n        brand {\n          id\n          name\n          slug\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query Sections($active: Boolean) {\n    sections(active: $active) {\n      id\n      title\n      title_en\n      title_ar\n      active\n      sort_order\n      section_type\n      created_at\n      updated_at\n      products_count\n      active_products_count\n      has_products\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        discount_percentage\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n        description\n        category {\n          id\n          name\n          slug\n        }\n        brand {\n          id\n          name\n          slug\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query SectionById($id: ID!) {\n    section(id: $id) {\n      id\n      title\n      title_en\n      title_ar\n      active\n      sort_order\n      section_type\n      created_at\n      updated_at\n      products_count\n      active_products_count\n      has_products\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        discount_percentage\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n        description\n        category {\n          id\n          name\n          slug\n        }\n        brand {\n          id\n          name\n          slug\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query SectionById($id: ID!) {\n    section(id: $id) {\n      id\n      title\n      title_en\n      title_ar\n      active\n      sort_order\n      section_type\n      created_at\n      updated_at\n      products_count\n      active_products_count\n      has_products\n      products {\n        id\n        name\n        slug\n        price\n        effective_price\n        discount_percentage\n        is_featured\n        is_on_sale\n        is_in_stock\n        featured_image\n        description\n        category {\n          id\n          name\n          slug\n        }\n        brand {\n          id\n          name\n          slug\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetWishlist {\n    wishlist {\n      id\n      user_id\n      product_id\n      created_at\n      product {\n        id\n        name\n        slug\n        price\n        sale_price\n        effective_price\n        featured_image\n        is_active\n        is_in_stock\n        category {\n          id\n          name\n        }\n        brand {\n          id\n          name\n        }\n        default_variant {\n          id\n          name\n          sku\n          price\n          sale_price\n          quantity\n          is_active\n          is_default\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetWishlist {\n    wishlist {\n      id\n      user_id\n      product_id\n      created_at\n      product {\n        id\n        name\n        slug\n        price\n        sale_price\n        effective_price\n        featured_image\n        is_active\n        is_in_stock\n        category {\n          id\n          name\n        }\n        brand {\n          id\n          name\n        }\n        default_variant {\n          id\n          name\n          sku\n          price\n          sale_price\n          quantity\n          is_active\n          is_default\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetWishlistCount {\n    wishlistCount\n  }\n"): (typeof documents)["\n  query GetWishlistCount {\n    wishlistCount\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation AddToWishlist($input: AddToWishlistInput!) {\n    addToWishlist(input: $input) {\n      id\n      user_id\n      product_id\n      created_at\n      product {\n        id\n        name\n        slug\n        price\n        sale_price\n        effective_price\n        featured_image\n        is_active\n        is_in_stock\n        category {\n          id\n          name\n        }\n        brand {\n          id\n          name\n        }\n        default_variant {\n          id\n          name\n          sku\n          price\n          sale_price\n          quantity\n          is_active\n          is_default\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation AddToWishlist($input: AddToWishlistInput!) {\n    addToWishlist(input: $input) {\n      id\n      user_id\n      product_id\n      created_at\n      product {\n        id\n        name\n        slug\n        price\n        sale_price\n        effective_price\n        featured_image\n        is_active\n        is_in_stock\n        category {\n          id\n          name\n        }\n        brand {\n          id\n          name\n        }\n        default_variant {\n          id\n          name\n          sku\n          price\n          sale_price\n          quantity\n          is_active\n          is_default\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RemoveFromWishlist($input: RemoveFromWishlistInput!) {\n    removeFromWishlist(input: $input)\n  }\n"): (typeof documents)["\n  mutation RemoveFromWishlist($input: RemoveFromWishlistInput!) {\n    removeFromWishlist(input: $input)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation MoveWishlistToCart(\n    $product_id: ID!\n    $product_variant_id: ID!\n    $quantity: Int!\n  ) {\n    moveWishlistToCart(\n      product_id: $product_id\n      product_variant_id: $product_variant_id\n      quantity: $quantity\n    ) {\n      id\n      cart_id\n      product_variant_id\n      quantity\n      unit_price\n      total_price\n      is_available\n      variant {\n        id\n        name\n        sku\n        price\n        sale_price\n        quantity\n        is_active\n        is_default\n      }\n      product {\n        id\n        name\n        slug\n        price\n        sale_price\n        effective_price\n        featured_image\n        is_active\n        is_in_stock\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation MoveWishlistToCart(\n    $product_id: ID!\n    $product_variant_id: ID!\n    $quantity: Int!\n  ) {\n    moveWishlistToCart(\n      product_id: $product_id\n      product_variant_id: $product_variant_id\n      quantity: $quantity\n    ) {\n      id\n      cart_id\n      product_variant_id\n      quantity\n      unit_price\n      total_price\n      is_available\n      variant {\n        id\n        name\n        sku\n        price\n        sale_price\n        quantity\n        is_active\n        is_default\n      }\n      product {\n        id\n        name\n        slug\n        price\n        sale_price\n        effective_price\n        featured_image\n        is_active\n        is_in_stock\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetNotifications($first: Int = 10, $page: Int = 1, $unread_only: Boolean = false) {\n    notifications(first: $first, page: $page, unread_only: $unread_only) {\n      data {\n        id\n        type\n        data\n        read_at\n        created_at\n        updated_at\n      }\n      paginatorInfo {\n        count\n        currentPage\n        firstItem\n        hasMorePages\n        lastItem\n        lastPage\n        perPage\n        total\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetNotifications($first: Int = 10, $page: Int = 1, $unread_only: Boolean = false) {\n    notifications(first: $first, page: $page, unread_only: $unread_only) {\n      data {\n        id\n        type\n        data\n        read_at\n        created_at\n        updated_at\n      }\n      paginatorInfo {\n        count\n        currentPage\n        firstItem\n        hasMorePages\n        lastItem\n        lastPage\n        perPage\n        total\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetUnreadNotificationsCount {\n    unreadNotificationsCount\n  }\n"): (typeof documents)["\n  query GetUnreadNotificationsCount {\n    unreadNotificationsCount\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation MarkNotificationAsRead($id: ID!) {\n    markNotificationAsRead(id: $id)\n  }\n"): (typeof documents)["\n  mutation MarkNotificationAsRead($id: ID!) {\n    markNotificationAsRead(id: $id)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation MarkAllNotificationsAsRead {\n    markAllNotificationsAsRead\n  }\n"): (typeof documents)["\n  mutation MarkAllNotificationsAsRead {\n    markAllNotificationsAsRead\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DeleteNotification($id: ID!) {\n    deleteNotification(id: $id)\n  }\n"): (typeof documents)["\n  mutation DeleteNotification($id: ID!) {\n    deleteNotification(id: $id)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation SendNotification($user_id: ID!, $notification: NotificationInput!) {\n    sendNotification(user_id: $user_id, notification: $notification)\n  }\n"): (typeof documents)["\n  mutation SendNotification($user_id: ID!, $notification: NotificationInput!) {\n    sendNotification(user_id: $user_id, notification: $notification)\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;